export const BUTTON_VARIANT_CONTAINED = 'contained';
export const BUTTON_VARIANT_OUTLINED = 'outlined';

export const BUTTON_VARIANT_LIST: readonly [typeof BUTTON_VARIANT_CONTAINED, typeof BUTTON_VARIANT_OUTLINED] = [
	BUTTON_VARIANT_CONTAINED,
	BUTTON_VARIANT_OUTLINED,
];
